// Curated names for the USDA "Nutritive Value of Foods" (Home and Garden Bulletin 72)
// CSV in this repo.
//
// Why this file exists: the CSV was extracted from the printed table, and the
// extraction dropped the left-most level of the publication's indented food
// hierarchy. Rows 1064-1069 are broccoli, for example, but the word "broccoli"
// appears nowhere in them - their `category` column holds a preparation
// fragment ("Raw", "From raw") inherited from a neighbouring heading, and the
// `food` column holds only the variant ("Chopped or diced", "Spear, about 5
// long"). Searching the raw CSV for a plain food name therefore misses most of
// the table.
//
// Each entry restores the missing name for a run of item numbers:
//   [idSpec, group, name, aliases, variant]
//     idSpec  - "1064" or "1064-1066" (inclusive), matched against food_no
//     group   - food group heading, for grouping and display
//     name    - the canonical searchable name
//     aliases - extra search terms (plurals, common names, synonyms)
//     variant - how to label the row within the name:
//                 undefined -> use the CSV `food` column (the variant text)
//                 null      -> no variant (the CSV `food` column is the name)
//                 string    -> use this literal text
//
// Item numbers absent from this table are dropped from the generated dataset.
// That currently covers blank/continuation rows in the CSV and item 3, whose
// nutrient columns were truncated during extraction.

const BEVERAGES = "Beverages";
const DAIRY = "Dairy and eggs";
const FATS = "Fats and oils";
const FISH = "Fish and shellfish";
const FRUIT = "Fruits and juices";
const GRAINS = "Grains and baked goods";
const CEREAL = "Breakfast cereals";
const LEGUMES = "Legumes, nuts, and seeds";
const MEAT = "Meat";
const POULTRY = "Poultry";
const MIXED = "Mixed dishes";
const FAST = "Fast foods";
const SOUP = "Soups, sauces, and gravies";
const SWEETS = "Sweets";
const VEG = "Vegetables";
const MISC = "Miscellaneous";

export const catalog = [
  // ---------------------------------------------------------------- Beverages
  ["32", BEVERAGES, "Cranberry juice cocktail", ["juice"], null],
  ["33", BEVERAGES, "Fruit punch drink", ["juice"], null],
  ["34", BEVERAGES, "Grape drink", ["juice"], null],
  ["35", BEVERAGES, "Pineapple grapefruit juice drink", ["juice"], null],
  ["36", BEVERAGES, "Pineapple orange juice drink", ["juice"], null],
  ["37-39", BEVERAGES, "Lemonade", []],
  ["40-41", BEVERAGES, "Malted milk, chocolate", ["malt", "milkshake"]],
  ["42-43", BEVERAGES, "Malted milk, natural", ["malt"]],
  ["44", BEVERAGES, "Rice beverage (RICE DREAM)", ["rice milk"], null],
  ["45", BEVERAGES, "Tea, brewed", ["black tea"]],
  ["46-47", BEVERAGES, "Tea, herb, brewed", ["herbal tea"]],
  ["48-50", BEVERAGES, "Tea, instant, prepared", ["iced tea"]],

  // ------------------------------------------------------------ Dairy and eggs
  ["52", DAIRY, "Blue cheese", ["bleu"], null],
  ["53", DAIRY, "Camembert cheese", [], null],
  ["54-56", DAIRY, "Cheddar cheese", ["cheese"]],
  ["57-62", DAIRY, "Cottage cheese", ["cheese"]],
  ["63-66", DAIRY, "Cream cheese", ["cheese"]],
  ["67", DAIRY, "Feta cheese", [], null],
  ["68", DAIRY, "Cheddar or colby cheese, low fat", ["cheese"], null],
  ["69-70", DAIRY, "Mozzarella cheese", ["cheese", "pizza cheese"]],
  ["71", DAIRY, "Muenster cheese", ["cheese"], null],
  ["72", DAIRY, "Neufchatel cheese", ["cheese"], null],
  ["73-75", DAIRY, "Parmesan cheese, grated", ["cheese"], null],
  ["76", DAIRY, "Provolone cheese", ["cheese"], null],
  ["77-78", DAIRY, "Ricotta cheese", ["cheese"]],
  ["79", DAIRY, "Swiss cheese", ["cheese"], null],
  [
    "80-81",
    DAIRY,
    "American cheese, pasteurized process",
    ["cheese", "cheese slice"],
  ],
  ["82", DAIRY, "Swiss cheese, pasteurized process", ["cheese"], null],
  ["83", DAIRY, "Pasteurized process cheese food, American", ["cheese"], null],
  [
    "84",
    DAIRY,
    "Pasteurized process cheese spread, American",
    ["cheese"],
    null,
  ],
  ["85-86", DAIRY, "Half and half cream", ["creamer"], null],
  ["87-88", DAIRY, "Light cream, coffee or table", ["creamer"], null],
  ["89-90", DAIRY, "Whipping cream, light", ["heavy cream"], null],
  ["91-92", DAIRY, "Whipping cream, heavy", ["heavy cream"], null],
  [
    "93-94",
    DAIRY,
    "Whipped cream topping, pressurized",
    ["whipped cream"],
    null,
  ],
  ["95-96", DAIRY, "Sour cream", [], "Regular"],
  ["97", DAIRY, "Sour cream, reduced fat", [], null],
  ["98", DAIRY, "Sour cream, fat free", [], null],
  ["99", DAIRY, "Cream substitute, liquid", ["coffee creamer"], null],
  ["100", DAIRY, "Cream substitute, powdered", ["coffee creamer"], null],
  [
    "101-102",
    DAIRY,
    "Whipped topping, frozen",
    ["cool whip", "whipped cream"],
    null,
  ],
  [
    "103-104",
    DAIRY,
    "Whipped topping, powdered, prepared",
    ["whipped cream"],
    null,
  ],
  ["105-106", DAIRY, "Whipped topping, pressurized", ["whipped cream"], null],
  ["107-108", DAIRY, "Sour dressing, nonbutterfat", [], null],
  ["109-110", DAIRY, "Frozen yogurt, soft serve", ["froyo"]],
  ["111-116", DAIRY, "Ice cream", ["dessert"]],
  ["117", DAIRY, "Sherbet, orange", ["sorbet"], null],
  ["118", DAIRY, "Milk, whole", ["dairy milk", "3.3%"], "3.3% fat"],
  ["119", DAIRY, "Milk, reduced fat (2%)", ["dairy milk"], null],
  ["120", DAIRY, "Milk, lowfat (1%)", ["dairy milk"], null],
  ["121", DAIRY, "Milk, nonfat (skim)", ["dairy milk", "fat free milk"], null],
  ["122", DAIRY, "Buttermilk", [], null],
  ["123", DAIRY, "Milk, sweetened condensed, canned", [], null],
  ["124", DAIRY, "Milk, evaporated, whole, canned", [], null],
  ["125", DAIRY, "Milk, evaporated, skim, canned", [], null],
  ["126", DAIRY, "Buttermilk, dried", [], null],
  ["128-130", DAIRY, "Chocolate milk", ["cocoa milk"]],
  ["131", DAIRY, "Eggnog", [], null],
  ["132-133", DAIRY, "Milk shake, thick", ["milkshake"]],
  ["134-135", DAIRY, "Yogurt, lowfat", ["yoghurt"]],
  ["136-137", DAIRY, "Yogurt, nonfat", ["yoghurt"]],
  ["138", DAIRY, "Yogurt, whole milk, plain", ["yoghurt"], null],
  ["139", DAIRY, "Yogurt, nonfat, low calorie", ["yoghurt"], null],
  ["140-142", DAIRY, "Egg, raw, whole", ["eggs"]],
  ["143", DAIRY, "Egg white, raw", ["eggs"], null],
  ["144", DAIRY, "Egg yolk, raw", ["eggs"], null],
  ["145", DAIRY, "Egg, fried", ["eggs"], null],
  ["146", DAIRY, "Egg, hard cooked", ["eggs", "hard boiled"], null],
  ["148", DAIRY, "Egg, poached", ["eggs"], null],
  ["149", DAIRY, "Egg, scrambled", ["eggs"], null],
  ["150", DAIRY, "Egg substitute, liquid", ["eggs", "egg beaters"], null],

  // ------------------------------------------------------------- Fats and oils
  ["151-153", FATS, "Butter, salted", [], "Salted"],
  ["154", FATS, "Butter, unsalted", [], null],
  ["155-156", FATS, "Lard", [], null],
  ["157-161", FATS, "Margarine, regular (about 80% fat)", []],
  ["162-166", FATS, "Margarine spread (about 60% fat)", []],
  ["167-168", FATS, "Margarine spread (about 40% fat)", [], null],
  ["169-170", FATS, "Margarine butter blend", [], null],
  ["171-172", FATS, "Canola oil", ["vegetable oil", "cooking oil"], null],
  ["173-174", FATS, "Corn oil", ["vegetable oil", "cooking oil"], null],
  ["175-176", FATS, "Olive oil", ["cooking oil"], null],
  ["177-178", FATS, "Peanut oil", ["cooking oil"], null],
  ["179-180", FATS, "Safflower oil", ["cooking oil"], null],
  ["181-182", FATS, "Sesame oil", ["cooking oil"], null],
  ["183-184", FATS, "Soybean oil", ["vegetable oil", "cooking oil"], null],
  [
    "185-186",
    FATS,
    "Soybean and cottonseed oil blend",
    ["vegetable oil"],
    null,
  ],
  ["187-188", FATS, "Sunflower oil", ["cooking oil"], null],
  ["189-190", FATS, "Salad dressing, blue cheese", ["dressing"]],
  ["191-192", FATS, "Salad dressing, caesar", ["dressing"]],
  ["193-194", FATS, "Salad dressing, french", ["dressing"]],
  ["195-196", FATS, "Salad dressing, italian", ["dressing"]],
  ["197", FATS, "Mayonnaise", ["mayo", "dressing"], "Regular"],
  ["199", FATS, "Mayonnaise, fat free", ["mayo", "dressing"], null],
  ["200-201", FATS, "Salad dressing, russian", ["dressing"]],
  ["202-203", FATS, "Salad dressing, thousand island", ["dressing"]],
  ["204", FATS, "Salad dressing, cooked, home recipe", ["dressing"], null],
  ["205", FATS, "Salad dressing, french, home recipe", ["dressing"], null],
  [
    "206",
    FATS,
    "Salad dressing, vinegar and oil",
    ["dressing", "vinaigrette"],
    null,
  ],
  ["207-208", FATS, "Shortening, vegetable", ["crisco"], null],

  // -------------------------------------------------------- Fish and shellfish
  ["209", FISH, "Catfish, breaded and fried", [], null],
  ["210-214", FISH, "Clams", ["shellfish"]],
  ["215-217", FISH, "Cod", []],
  ["218-219", FISH, "Crab, Alaska king", ["shellfish"], "Steamed"],
  ["220", FISH, "Crab, imitation, from surimi", ["shellfish"], null],
  ["221-222", FISH, "Crab, blue", ["shellfish"]],
  ["223", FISH, "Crab cake", ["shellfish"], null],
  [
    "224",
    FISH,
    "Fish fillet, battered or breaded, fried",
    ["fish sticks"],
    null,
  ],
  ["227-228", FISH, "Flounder or sole, baked or broiled", [], null],
  ["229-230", FISH, "Haddock, baked or broiled", [], null],
  ["231-232", FISH, "Halibut, baked or broiled", [], null],
  ["233", FISH, "Herring, pickled", [], null],
  ["234", FISH, "Lobster, steamed", ["shellfish"], null],
  ["235-236", FISH, "Ocean perch, baked or broiled", [], null],
  ["237-239", FISH, "Oysters", ["shellfish"]],
  ["240-241", FISH, "Pollock, baked or broiled", [], null],
  ["242-243", FISH, "Rockfish, baked or broiled", [], null],
  ["244", FISH, "Orange roughy, baked or broiled", [], null],
  ["245-246", FISH, "Salmon, baked or broiled", [], "Red (sockeye)"],
  ["247", FISH, "Salmon, canned pink, with bones", [], null],
  ["248", FISH, "Salmon, smoked (lox)", [], null],
  ["249", FISH, "Sardines, Atlantic, canned in oil", [], null],
  ["250-251", FISH, "Scallops", ["shellfish"]],
  ["252-254", FISH, "Shrimp", ["shellfish", "prawns"]],
  ["255-256", FISH, "Swordfish, baked or broiled", [], null],
  ["257-258", FISH, "Trout, baked or broiled", [], null],
  ["259", FISH, "Tuna, baked or broiled", [], null],
  ["260", FISH, "Tuna, canned", [], "Oil pack, chunk light"],
  ["263", FISH, "Tuna salad", [], null],

  // ------------------------------------------------------------------- Fruits
  ["265-266", FRUIT, "Apples, raw", ["apple"]],
  ["267", FRUIT, "Apple juice", ["apple", "juice"], null],
  ["268", FRUIT, "Apple pie filling, canned", ["apple"], null],
  ["269-270", FRUIT, "Applesauce, canned", ["apple"]],
  ["271", FRUIT, "Apricots, raw", ["apricot"], null],
  ["272-273", FRUIT, "Apricots, canned", ["apricot"]],
  ["274", FRUIT, "Apricots, dried", ["apricot"], null],
  ["276-277", FRUIT, "Asian pears, raw", ["pear"]],
  ["278-279", FRUIT, "Avocados, raw", ["avocado", "guacamole"]],
  ["280-281", FRUIT, "Bananas, raw", ["banana"]],
  ["282", FRUIT, "Blackberries, raw", ["berries"], null],
  ["283-284", FRUIT, "Blueberries", ["berries"]],
  ["285-286", FRUIT, "Carambola (starfruit), raw", ["star fruit"]],
  ["288", FRUIT, "Cherries, sweet, raw", ["cherry"], null],
  ["289", FRUIT, "Cherry pie filling, canned", ["cherries"], null],
  ["290", FRUIT, "Cranberries, dried, sweetened", ["craisins"], null],
  ["291", FRUIT, "Cranberry sauce, canned", ["cranberries"], null],
  ["292-293", FRUIT, "Dates", ["date"]],
  ["294", FRUIT, "Figs, dried", ["fig"], null],
  ["295-296", FRUIT, "Fruit cocktail, canned", ["fruit salad"]],
  ["297-298", FRUIT, "Grapefruit, raw", []],
  ["299", FRUIT, "Grapefruit, canned sections", [], null],
  ["300-301", FRUIT, "Grapefruit juice, raw", ["juice"]],
  ["302-303", FRUIT, "Grapefruit juice, canned", ["juice"]],
  [
    "304",
    FRUIT,
    "Grapefruit juice, frozen concentrate",
    ["juice"],
    "Undiluted, 6 fl oz can",
  ],
  ["306-307", FRUIT, "Grapes, seedless, raw", ["grape"], null],
  ["308", FRUIT, "Grape juice, canned or bottled", ["juice"], null],
  [
    "309",
    FRUIT,
    "Grape juice, frozen concentrate",
    ["juice"],
    "Undiluted, 6 fl oz can",
  ],
  ["311", FRUIT, "Kiwi fruit, raw", ["kiwifruit"], null],
  ["312", FRUIT, "Lemons, raw", ["lemon"], null],
  ["313-315", FRUIT, "Lemon juice", ["juice"]],
  ["316-318", FRUIT, "Lime juice", ["juice"]],
  ["319-320", FRUIT, "Mangos, raw", ["mango"]],
  ["321-322", FRUIT, "Cantaloupe, raw", ["melon"]],
  ["323-324", FRUIT, "Honeydew melon, raw", ["melon"]],
  ["325", FRUIT, "Mixed fruit, frozen, sweetened", ["fruit salad"], null],
  ["326", FRUIT, "Nectarines, raw", ["nectarine"], null],
  ["327-328", FRUIT, "Oranges, raw", ["orange"]],
  ["329-330", FRUIT, "Orange juice, raw", ["juice"]],
  ["331", FRUIT, "Orange juice, canned", ["juice"], null],
  ["332", FRUIT, "Orange juice, chilled", ["juice"], null],
  [
    "333",
    FRUIT,
    "Orange juice, frozen concentrate",
    ["juice"],
    "Undiluted, 6 fl oz can",
  ],
  ["336", FRUIT, "Papayas, raw", ["papaya"], null],
  ["337-338", FRUIT, "Peaches, raw", ["peach"]],
  ["339-342", FRUIT, "Peaches, canned", ["peach"]],
  ["343", FRUIT, "Peaches, dried", ["peach"], null],
  ["344", FRUIT, "Peaches, frozen, sweetened", ["peach"], null],
  ["345", FRUIT, "Pears, raw", ["pear"], null],
  ["346-349", FRUIT, "Pears, canned", ["pear"]],
  ["350", FRUIT, "Pineapple, raw", [], null],
  ["351-352", FRUIT, "Pineapple, canned in heavy syrup", []],
  ["353-354", FRUIT, "Pineapple, canned in juice", []],
  ["355", FRUIT, "Pineapple juice, canned", ["juice"], null],
  ["356-357", FRUIT, "Plantains", ["plantain"]],
  ["358", FRUIT, "Plums, raw", ["plum"], null],
  ["359-362", FRUIT, "Plums, canned, purple", ["plum"]],
  ["363-364", FRUIT, "Prunes, dried", ["prune", "dried plums"]],
  ["365", FRUIT, "Prune juice, canned or bottled", ["juice"], null],
  ["366-367", FRUIT, "Raisins, seedless", ["raisin"]],
  ["368-369", FRUIT, "Raspberries", ["berries"]],
  ["370", FRUIT, "Rhubarb, frozen, cooked with sugar", [], null],
  ["371-374", FRUIT, "Strawberries", ["berries", "strawberry"]],
  ["375", FRUIT, "Tangerines, raw", ["tangerine", "clementine"], null],
  ["376", FRUIT, "Tangerines, canned (mandarin oranges)", ["mandarin"], null],
  ["377", FRUIT, "Tangerine juice, canned", ["juice"], null],
  ["378-379", FRUIT, "Watermelon, raw", ["melon"]],

  // ------------------------------------------------- Grains and baked goods
  ["380-381", GRAINS, "Bagel, plain", ["bagels"]],
  ["382-383", GRAINS, "Bagel, cinnamon raisin", ["bagels"]],
  ["384-385", GRAINS, "Bagel, egg", ["bagels"]],
  ["386", GRAINS, "Banana bread", [], null],
  ["387-388", GRAINS, "Barley, pearled", []],
  [
    "389-390",
    GRAINS,
    "Biscuit, plain or buttermilk, from recipe",
    ["biscuits"],
  ],
  ["391-392", GRAINS, "Biscuit, from refrigerated dough", ["biscuits"]],
  ["393", GRAINS, "Bread, cracked wheat", [], null],
  ["394", GRAINS, "Bread, egg (challah)", [], null],
  ["395", GRAINS, "Bread, french or vienna", ["sourdough"], null],
  ["396-397", GRAINS, "Bread, Indian fry (navajo)", [], null],
  ["398", GRAINS, "Bread, italian", [], null],
  ["399-400", GRAINS, "Bread, mixed grain", ["multigrain"]],
  ["401-402", GRAINS, "Bread, oatmeal", []],
  ["403-404", GRAINS, "Pita bread", ["pocket bread"], null],
  ["405-406", GRAINS, "Bread, pumpernickel", []],
  ["407-408", GRAINS, "Bread, raisin", []],
  ["409-410", GRAINS, "Bread, rye", []],
  ["411", GRAINS, "Bread, rye, reduced calorie", [], null],
  ["412-413", GRAINS, "Bread, wheat", []],
  ["414", GRAINS, "Bread, wheat, reduced calorie", [], null],
  ["415-417", GRAINS, "Bread, white", []],
  ["418", GRAINS, "Bread, white, reduced calorie", [], null],
  ["419-420", GRAINS, "Bread, whole wheat", []],
  ["421-423", GRAINS, "Bread crumbs, dry, grated", []],
  ["424", GRAINS, "Bread stuffing, from dry mix", [], null],
  ["425", GRAINS, "Breakfast bar, fruit filled, fat free", [], null],
  ["426-428", GRAINS, "Corn grits, cooked", ["hominy grits"]],
  ["429-431", CEREAL, "CREAM OF WHEAT, cooked", ["farina", "hot cereal"]],
  ["432", CEREAL, "MALT-O-MEAL, cooked", ["hot cereal"], null],
  [
    "433",
    CEREAL,
    "Oatmeal, cooked",
    ["oats", "porridge", "hot cereal"],
    "Regular, quick or instant, plain",
  ],
  ["434", CEREAL, "Oatmeal, instant, fortified", ["oats", "hot cereal"], null],
  [
    "435-436",
    CEREAL,
    "QUAKER instant oatmeal, flavored",
    ["oats", "hot cereal"],
  ],
  ["437", CEREAL, "WHEATENA, cooked", ["hot cereal"], null],

  // Ready-to-eat cereals: one row each, already named in the CSV `food` column.
  ["438-446", CEREAL, null, ["cereal"], null],
  ["447-451", CEREAL, "CHEX cereal", ["cereal"]],
  ["452-455", CEREAL, null, ["cereal"], null],
  ["456-457", CEREAL, "Corn Flakes", ["cereal"]],
  ["458-462", CEREAL, null, ["cereal"], null],
  ["463-464", CEREAL, "FROSTED MINI WHEATS", ["cereal"]],
  ["465-471", CEREAL, null, ["cereal"], null],
  ["472-474", CEREAL, "NATURE VALLEY Granola", ["cereal", "granola"]],
  ["475-477", CEREAL, null, ["cereal"], null],
  ["478-479", CEREAL, "Raisin Bran", ["cereal"]],
  ["480-490", CEREAL, null, ["cereal"], null],

  ["491-493", GRAINS, "Brownies", ["brownie", "dessert"]],
  ["494", GRAINS, "Buckwheat flour, whole groat", [], null],
  ["495", GRAINS, "Buckwheat groats, roasted (kasha), cooked", [], null],
  ["496-497", GRAINS, "Bulgur", []],
  ["498", GRAINS, "Cake, angelfood, from dry mix", ["dessert"], null],
  [
    "500",
    GRAINS,
    "Cake, chocolate, from recipe, without frosting",
    ["dessert"],
    null,
  ],
  ["501", GRAINS, "Gingerbread, from recipe", ["cake", "dessert"], null],
  [
    "502",
    GRAINS,
    "Cake, pineapple upside down, from recipe",
    ["dessert"],
    null,
  ],
  ["503", GRAINS, "Shortcake, biscuit type", ["dessert"], null],
  ["504", GRAINS, "Cake, sponge, from recipe", ["dessert"], null],
  ["505-506", GRAINS, "Cake, white, from recipe", ["dessert"]],
  ["507", GRAINS, "Cake, angelfood, commercially prepared", ["dessert"], null],
  ["508", GRAINS, "Boston cream pie", ["cake", "dessert"], null],
  ["509", GRAINS, "Cake, chocolate with chocolate frosting", ["dessert"], null],
  ["510", GRAINS, "Coffeecake, crumb", ["dessert"], null],
  ["511", GRAINS, "Fruitcake", ["dessert"], null],
  ["512", GRAINS, "Pound cake, butter", ["dessert"], null],
  ["513", GRAINS, "Pound cake, fat free", ["dessert"], null],
  ["514-517", GRAINS, "Snack cakes", ["dessert", "cupcake"]],
  ["518-519", GRAINS, "Cake, yellow, with frosting", ["dessert"]],
  ["520", GRAINS, "Cheesecake", ["dessert"], null],
  ["521", GRAINS, "Cheese puffs or twists", ["snack", "cheetos"], null],
  ["522", GRAINS, "CHEX mix", ["snack"], null],
  ["523", GRAINS, "Cookie, butter", ["cookies"], null],
  ["524-527", GRAINS, "Cookie, chocolate chip", ["cookies"]],
  ["528", GRAINS, "Cookie, devil's food, fat free", ["cookies"], null],
  ["529", GRAINS, "Cookie, fig bar", ["cookies", "fig newton"], null],
  ["530-531", GRAINS, "Cookie, molasses", ["cookies"]],
  ["532-535", GRAINS, "Cookie, oatmeal", ["cookies"]],
  ["536-537", GRAINS, "Cookie, peanut butter", ["cookies"]],
  [
    "538",
    GRAINS,
    "Cookie, chocolate sandwich with creme",
    ["cookies", "oreo"],
    null,
  ],
  ["539-540", GRAINS, "Cookie, vanilla sandwich with creme", ["cookies"]],
  ["541", GRAINS, "Cookie, shortbread", ["cookies"], null],
  ["542-543", GRAINS, "Cookie, shortbread, pecan", ["cookies"]],
  ["544-546", GRAINS, "Cookie, sugar", ["cookies"]],
  ["547", GRAINS, "Cookie, vanilla wafer, lower fat", ["cookies"], null],
  ["548-549", GRAINS, "Corn chips", ["snack"]],
  ["550-551", GRAINS, "Cornbread", []],
  ["552-554", GRAINS, "Cornmeal, yellow, dry", []],
  ["555", GRAINS, "Cornstarch", [], null],
  ["556-557", GRAINS, "Couscous", []],
  ["558", GRAINS, "Crackers, cheese", [], null],
  ["559-560", GRAINS, "Crackers, graham", ["graham cracker"]],
  ["561", GRAINS, "Melba toast, plain", ["crackers"], null],
  ["562", GRAINS, "Rye wafer, whole grain", ["crackers"], null],
  ["563-564", GRAINS, "Crackers, saltine", ["soda crackers"]],
  ["565-566", GRAINS, "Crackers, sandwich type", []],
  ["567-568", GRAINS, "Crackers, standard snack type", ["ritz"]],
  ["569", GRAINS, "Crackers, wheat, thin square", [], null],
  ["570", GRAINS, "Crackers, whole wheat", [], null],
  ["571", GRAINS, "Croissant, butter", [], null],
  ["572", GRAINS, "Croutons, seasoned", [], null],
  ["573-574", GRAINS, "Danish pastry", []],
  ["575-576", GRAINS, "Doughnut, cake type", ["donut"], null],
  ["577-578", GRAINS, "Doughnut, yeast leavened, glazed", ["donut"], null],
  ["579", GRAINS, "Eclair, from recipe", ["dessert"], null],
  ["580-581", GRAINS, "English muffin, plain", []],
  ["582-583", GRAINS, "French toast", []],
  ["584", GRAINS, "Granola bar, hard, plain", [], null],
  ["585-586", GRAINS, "Granola bar, soft, uncoated", []],
  ["587", GRAINS, "Granola bar, chocolate coated, peanut butter", [], null],
  ["588", GRAINS, "Macaroni, enriched, cooked", ["pasta", "elbows"], null],
  ["589", GRAINS, "Matzo, plain", [], null],
  ["590-592", GRAINS, "Muffin, blueberry", ["muffins"]],
  ["593", GRAINS, "Muffin, bran with raisins, toaster type", ["muffins"], null],
  ["594-595", GRAINS, "Muffin, corn", ["muffins"]],
  ["596", GRAINS, "Muffin, oat bran", ["muffins"], null],
  ["597", GRAINS, "Noodles, chow mein, canned", ["pasta"], null],
  ["598-599", GRAINS, "Noodles, egg, cooked", ["pasta"]],
  ["600", GRAINS, "NUTRI-GRAIN cereal bar, fruit filled", [], null],
  ["601-602", GRAINS, "Oat bran", []],
  ["603", GRAINS, "Oriental snack mix", ["snack"], null],
  ["604-606", GRAINS, "Pancakes", ["pancake", "flapjacks"]],
  ["607-608", GRAINS, "Pie crust, standard", ["pastry shell"]],
  ["609", GRAINS, "Pie crust, graham cracker", [], null],
  ["610-617", GRAINS, "Pie, commercially prepared", ["dessert"]],
  ["618-623", GRAINS, "Pie, prepared from recipe", ["dessert"]],
  ["624", GRAINS, "Pie, fried, cherry", ["dessert"], null],
  ["625-626", GRAINS, "Popcorn", ["snack"]],
  ["627-628", GRAINS, "Popcorn, caramel coated", ["snack", "cracker jack"]],
  ["629", GRAINS, "Popcorn, cheese flavor", ["snack"], null],
  ["630", GRAINS, "Popcorn cake", ["snack"], null],
  ["631-633", GRAINS, "Pretzels", ["snack", "pretzel"]],
  ["634", GRAINS, "Rice, brown, long grain, cooked", [], null],
  ["635-637", GRAINS, "Rice, white, long grain, regular", []],
  ["638-639", GRAINS, "Rice, white, long grain, parboiled", ["converted rice"]],
  ["640", GRAINS, "Wild rice, cooked", [], null],
  ["641", GRAINS, "Rice cake, brown rice, plain", ["snack"], null],
  ["642", GRAINS, "RICE KRISPIES Treat Squares", ["snack"], null],
  ["643", GRAINS, "Roll, dinner", ["rolls", "bread"], null],
  [
    "644",
    GRAINS,
    "Roll, hamburger or hotdog bun",
    ["rolls", "buns", "bread"],
    null,
  ],
  ["645", GRAINS, "Roll, hard, kaiser", ["rolls", "bread"], null],
  ["646-647", GRAINS, "Spaghetti, cooked", ["pasta", "noodles"]],
  ["648-649", GRAINS, "Sweet roll, cinnamon", ["cinnamon bun"]],
  ["650", GRAINS, "Taco shell, baked", [], null],
  ["651", GRAINS, "Tapioca, pearl, dry", [], null],
  ["652-655", GRAINS, "Toaster pastries", ["pop tarts"]],
  ["656-657", GRAINS, "Tortilla chips, plain", ["snack"]],
  ["658-659", GRAINS, "Tortilla chips, nacho flavor", ["snack"]],
  ["660", GRAINS, "Tortillas, corn", ["tortilla"], null],
  ["661", GRAINS, "Tortillas, flour", ["tortilla", "wrap"], null],
  ["662-664", GRAINS, "Waffles", ["waffle"]],
  ["665-666", GRAINS, "Flour, all purpose, enriched", []],
  ["667", GRAINS, "Flour, bread, enriched", [], null],
  ["668", GRAINS, "Flour, cake or pastry, enriched", [], null],
  ["669", GRAINS, "Flour, self rising, enriched", [], null],
  ["670", GRAINS, "Flour, whole wheat", [], null],
  ["671", GRAINS, "Wheat germ, toasted", [], null],

  // ------------------------------------------------ Legumes, nuts, and seeds
  ["672-673", LEGUMES, "Almonds, shelled", ["almond", "nuts"]],
  ["674", LEGUMES, "Beans, black, cooked", ["black beans"], null],
  ["675", LEGUMES, "Beans, great northern, cooked", [], null],
  ["676", LEGUMES, "Beans, kidney, red, cooked", ["kidney beans"], null],
  ["677", LEGUMES, "Beans, lima, large, cooked", ["lima beans"], null],
  ["678", LEGUMES, "Beans, navy (pea), cooked", ["navy beans"], null],
  ["679", LEGUMES, "Beans, pinto, cooked", ["pinto beans"], null],
  ["680", LEGUMES, "Baked beans, plain or vegetarian, canned", [], null],
  [
    "681",
    LEGUMES,
    "Baked beans with franks, canned",
    ["beans and weiners"],
    null,
  ],
  ["682", LEGUMES, "Baked beans with pork in tomato sauce, canned", [], null],
  ["683", LEGUMES, "Baked beans with pork in sweet sauce, canned", [], null],
  ["684", LEGUMES, "Beans, kidney, red, canned", ["kidney beans"], null],
  ["685", LEGUMES, "Beans, lima, large, canned", ["lima beans"], null],
  ["686", LEGUMES, "Beans, white, canned", ["cannellini"], null],
  ["687", LEGUMES, "Black-eyed peas, dry, cooked", ["cowpeas"], null],
  ["688", LEGUMES, "Black-eyed peas, canned", ["cowpeas"], null],
  ["689", LEGUMES, "Brazil nuts, shelled", ["nuts"], null],
  ["690", LEGUMES, "Carob flour", [], null],
  ["691", LEGUMES, "Cashews, dry roasted, salted", ["nuts"], null],
  ["692-693", LEGUMES, "Cashews, oil roasted, salted", ["nuts"], null],
  ["694", LEGUMES, "Chestnuts, European, roasted", ["nuts"], null],
  ["695", LEGUMES, "Chickpeas, cooked", ["garbanzo beans"], null],
  ["696", LEGUMES, "Chickpeas, canned", ["garbanzo beans"], null],
  ["697-698", LEGUMES, "Coconut, raw", []],
  ["699", LEGUMES, "Coconut, dried, sweetened, shredded", [], null],
  ["700-701", LEGUMES, "Hazelnuts (filberts), chopped", ["nuts"], null],
  ["702", LEGUMES, "Hummus, commercial", ["chickpea dip"], null],
  ["703", LEGUMES, "Lentils, dry, cooked", ["lentil"], null],
  ["704", LEGUMES, "Macadamia nuts, dry roasted, salted", ["nuts"], null],
  ["706-707", LEGUMES, "Mixed nuts, with peanuts", ["nuts"]],
  ["708-710", LEGUMES, "Peanuts, dry roasted", ["nuts"]],
  ["711-712", LEGUMES, "Peanuts, oil roasted, salted", ["nuts"], null],
  ["713-714", LEGUMES, "Peanut butter", ["pb"]],
  ["715", LEGUMES, "Peanut butter, reduced fat", ["pb"], null],
  ["716", LEGUMES, "Peas, split, dry, cooked", ["split peas"], null],
  ["717-718", LEGUMES, "Pecans", ["nuts"], null],
  ["719-720", LEGUMES, "Pine nuts (pignolia), shelled", ["nuts"], null],
  ["721", LEGUMES, "Pistachio nuts, dry roasted, salted", ["nuts"], null],
  [
    "722",
    LEGUMES,
    "Pumpkin and squash seed kernels, roasted",
    ["seeds", "pepitas"],
    null,
  ],
  ["723", LEGUMES, "Refried beans, canned", [], null],
  ["724", LEGUMES, "Sesame seeds", ["seeds"], null],
  ["725", LEGUMES, "Soybeans, dry, cooked", [], null],
  ["726", LEGUMES, "Miso", ["soy"], null],
  ["727", LEGUMES, "Soy milk", ["soymilk"], null],
  ["728-729", LEGUMES, "Tofu", ["bean curd", "soy"]],
  [
    "730-731",
    LEGUMES,
    "Sunflower seed kernels, dry roasted, salted",
    ["seeds"],
    null,
  ],
  ["732", LEGUMES, "Tahini", ["sesame paste"], null],
  ["733-734", LEGUMES, "Walnuts, English", ["nuts"], null],

  // --------------------------------------------------------------------- Meat
  ["735-736", MEAT, "Beef, chuck blade roast, braised", ["pot roast"]],
  ["737-738", MEAT, "Beef, bottom round, braised", []],
  ["739-741", MEAT, "Ground beef, broiled", ["hamburger", "mince"]],
  ["742", MEAT, "Beef liver, fried", [], null],
  ["743-744", MEAT, "Beef, rib roast, roasted", ["prime rib"]],
  ["745-746", MEAT, "Beef, eye of round, roasted", []],
  ["747-748", MEAT, "Beef, sirloin steak, broiled", ["steak"]],
  ["749", MEAT, "Beef, corned, canned", [], null],
  ["750", MEAT, "Beef, dried, chipped", [], null],
  ["751-752", MEAT, "Lamb, arm chop, braised", []],
  ["753-754", MEAT, "Lamb, loin chop, broiled", []],
  ["755-756", MEAT, "Lamb, leg, roasted", []],
  ["757-758", MEAT, "Lamb, rib, roasted", []],
  ["759", MEAT, "Bacon, regular", ["pork"], null],
  ["760", MEAT, "Bacon, canadian style", ["pork"], null],
  ["761-762", MEAT, "Ham, cured, roasted", ["pork"]],
  ["763", MEAT, "Ham, canned, roasted", ["pork"], null],
  ["764-765", MEAT, "Pork loin chop, broiled", ["pork chop"]],
  ["766-767", MEAT, "Pork loin chop, pan fried", ["pork chop"]],
  ["768-769", MEAT, "Pork, fresh ham (leg), roasted", []],
  ["770-771", MEAT, "Pork, rib roast, roasted", []],
  ["772", MEAT, "Pork backribs, roasted", ["ribs"], null],
  ["773", MEAT, "Pork country style ribs, braised", ["ribs"], null],
  ["774", MEAT, "Pork spareribs, braised", ["ribs"], null],
  ["775-776", MEAT, "Pork shoulder cut, braised", []],
  ["777", MEAT, "Bologna, beef and pork", ["lunch meat", "deli"], null],
  ["778", MEAT, "Braunschweiger", ["liverwurst", "deli"], null],
  ["779", MEAT, "Sausage, brown and serve, cooked", [], null],
  [
    "780",
    MEAT,
    "Luncheon meat, pork, ham and chicken, canned, reduced sodium",
    ["spam", "deli"],
    null,
  ],
  ["781", MEAT, "Luncheon meat, pork with ham, canned", ["spam", "deli"], null],
  ["782", MEAT, "Luncheon meat, pork and chicken, canned", ["deli"], null],
  ["783", MEAT, "Ham, chopped", ["lunch meat", "deli"], null],
  ["784", MEAT, "Ham, cooked, sliced", ["lunch meat", "deli"], "Regular"],
  [
    "785",
    MEAT,
    "Ham, cooked, sliced, extra lean",
    ["lunch meat", "deli"],
    null,
  ],
  ["786", MEAT, "Frankfurter, beef and pork", ["hot dog", "wiener"], null],
  ["787", MEAT, "Frankfurter, beef", ["hot dog", "wiener"], null],
  ["788-789", MEAT, "Pork sausage, fresh, cooked", ["breakfast sausage"]],
  ["790", MEAT, "Salami, cooked type, beef and pork", ["deli"], null],
  ["791", MEAT, "Salami, dry type, beef and pork", ["deli"], null],
  ["792", MEAT, "Sandwich spread, pork and beef", [], null],
  ["793", MEAT, "Vienna sausage, canned", [], null],
  ["794", MEAT, "Veal cutlet, braised", [], null],
  ["795", MEAT, "Veal rib, roasted", [], null],

  // ------------------------------------------------------------- Mixed dishes
  ["796-807", MIXED, null, [], null],

  // ---------------------------------------------------------------- Fast foods
  ["808", FAST, "Biscuit with egg and sausage", ["breakfast sandwich"], null],
  [
    "809",
    FAST,
    "Croissant with egg, cheese and bacon",
    ["breakfast sandwich"],
    null,
  ],
  ["810", FAST, "Danish pastry, cheese filled", [], null],
  ["811", FAST, "Danish pastry, fruit filled", [], null],
  [
    "812",
    FAST,
    "English muffin with egg, cheese and canadian bacon",
    ["breakfast sandwich"],
    null,
  ],
  ["813", FAST, "French toast with butter", [], null],
  ["814", FAST, "French toast sticks", [], null],
  ["815", FAST, "Hashed brown potatoes, fast food", ["hash browns"], null],
  ["816", FAST, "Pancakes with butter and syrup", [], null],
  ["817", FAST, "Burrito with beans and cheese", [], null],
  ["818", FAST, "Burrito with beans and meat", [], null],
  ["819-820", FAST, "Cheeseburger, regular, with condiments", ["burger"]],
  ["821-823", FAST, "Cheeseburger, regular, plain", ["burger"]],
  ["824-825", FAST, "Cheeseburger, large, with condiments", ["burger"]],
  [
    "826",
    FAST,
    "Chicken fillet sandwich, breaded and fried",
    ["chicken sandwich"],
    null,
  ],
  ["827", FAST, "Chicken nuggets, breaded and fried", ["chicken pieces"], null],
  ["828", FAST, "Chili con carne, fast food", [], null],
  ["829", FAST, "Chimichanga with beef", [], null],
  ["830", FAST, "Coleslaw, fast food", ["cole slaw"], null],
  ["831", FAST, "Ice milk cone, soft serve vanilla", ["ice cream cone"], null],
  ["832", FAST, "Fried pie with fruit filling", [], null],
  ["833", FAST, "Hot fudge sundae", ["ice cream"], null],
  ["834", FAST, "Enchilada with cheese", [], null],
  ["835", FAST, "Fish sandwich with tartar sauce and cheese", [], null],
  ["836-838", FAST, "French fries", ["fries", "chips"], null],
  ["839", FAST, "Frijoles with cheese", ["refried beans"], null],
  ["840-841", FAST, "Hamburger, regular, with condiments", ["burger"]],
  ["842-843", FAST, "Hamburger, large, with condiments", ["burger"]],
  ["844", FAST, "Hot dog, plain", ["frankfurter"], null],
  ["845", FAST, "Hot dog with chili", ["chili dog"], null],
  ["846", FAST, "Corndog", ["corn dog", "hot dog"], null],
  ["847", FAST, "Hush puppies", [], null],
  ["848", FAST, "Mashed potatoes, fast food", [], null],
  ["849", FAST, "Nachos with cheese sauce", [], null],
  ["850", FAST, "Onion rings, breaded and fried", [], null],
  ["851", FAST, "Pizza, cheese", [], null],
  ["852", FAST, "Pizza with meat and vegetables", [], null],
  ["853", FAST, "Pizza, pepperoni", [], null],
  ["854", FAST, "Roast beef sandwich, plain", [], null],
  ["855", FAST, "Salad, tossed, with chicken, no dressing", [], null],
  ["856", FAST, "Salad, tossed, with egg and cheese, no dressing", [], null],
  ["857-858", FAST, "Milk shake, fast food", ["milkshake"]],
  ["859", FAST, "Shrimp, breaded and fried, fast food", [], null],
  ["860", FAST, "Submarine sandwich with cold cuts", ["sub", "hoagie"], null],
  ["861", FAST, "Submarine sandwich with roast beef", ["sub", "hoagie"], null],
  ["862", FAST, "Submarine sandwich with tuna salad", ["sub", "hoagie"], null],
  ["863-864", FAST, "Taco, beef", ["tacos"], null],
  ["865", FAST, "Taco salad with ground beef and cheese", [], null],
  ["866", FAST, "Tostada with beans and beef", [], null],
  ["867", FAST, "Tostada with guacamole", [], null],

  // ------------------------------------------------------------------ Poultry
  [
    "868-871",
    POULTRY,
    "Chicken, fried, batter dipped, with skin",
    ["fried chicken"],
  ],
  [
    "872-873",
    POULTRY,
    "Chicken, fried, flour coated, with skin",
    ["fried chicken"],
  ],
  ["874-875", POULTRY, "Chicken, fried, meat only", ["fried chicken"]],
  ["876-878", POULTRY, "Chicken, roasted, meat only", ["baked chicken"]],
  ["879", POULTRY, "Chicken, stewed, meat only, chopped", [], null],
  ["880", POULTRY, "Chicken giblets, simmered", [], null],
  ["881", POULTRY, "Chicken liver, simmered", [], null],
  ["882", POULTRY, "Chicken neck, meat only, simmered", [], null],
  ["883", POULTRY, "Duck, roasted, flesh only", [], null],
  ["884-886", POULTRY, "Turkey, roasted, meat only", []],
  ["887-888", POULTRY, "Ground turkey, cooked", []],
  ["889", POULTRY, "Turkey giblets, simmered", [], null],
  ["890", POULTRY, "Turkey neck, meat only, simmered", [], null],
  ["891", POULTRY, "Chicken, canned, boneless", [], null],
  ["892", POULTRY, "Chicken frankfurter", ["hot dog"], null],
  ["893", POULTRY, "Chicken roll, light meat", ["deli", "lunch meat"], null],
  ["894", POULTRY, "Gravy and turkey, frozen", [], null],
  ["895", POULTRY, "Turkey patties, breaded or battered, fried", [], null],
  ["896", POULTRY, "Turkey roast, boneless, frozen, seasoned", [], null],

  // ------------------------------------------------- Soups, sauces, and gravies
  ["897-900", SOUP, "Soup, canned condensed, prepared with milk", []],
  ["901-913", SOUP, "Soup, canned condensed, prepared with water", []],
  ["914-917", SOUP, "Soup, canned, ready to serve", []],
  ["918-925", SOUP, "Soup, canned, ready to serve, reduced fat and sodium", []],
  ["926-927", SOUP, "Soup mix, dehydrated, unprepared", ["bouillon"]],
  ["928-929", SOUP, "Soup, dehydrated, prepared with water", []],
  ["930-932", SOUP, "Soup stock, home prepared", ["broth"]],
  ["933", SOUP, "Cheese sauce, home recipe", [], null],
  ["934", SOUP, "White sauce, medium, home recipe", ["bechamel"], null],
  ["935", SOUP, "Barbecue sauce", ["bbq"], null],
  ["936", SOUP, "Cheese sauce, ready to serve", [], null],
  ["937", SOUP, "Hoisin sauce", [], null],
  ["938", SOUP, "Nacho cheese sauce", [], null],
  ["939", SOUP, "Hot pepper sauce", ["hot sauce", "tabasco"], null],
  ["940", SOUP, "Salsa", [], null],
  ["941", SOUP, "Soy sauce", [], null],
  ["942", SOUP, "Spaghetti, marinara or pasta sauce", ["tomato sauce"], null],
  ["943", SOUP, "Teriyaki sauce", [], null],
  ["944", SOUP, "Tomato chili sauce", [], null],
  ["945", SOUP, "Worcestershire sauce", [], null],
  ["946-950", SOUP, "Gravy, canned", []],

  // ------------------------------------------------------------------- Sweets
  ["951", SWEETS, "BUTTERFINGER bar", ["candy"], null],
  ["952", SWEETS, "Caramels, plain", ["candy"], null],
  [
    "953",
    SWEETS,
    "Caramel, chocolate flavored roll",
    ["candy", "tootsie roll"],
    null,
  ],
  ["954", SWEETS, "Carob candy", [], null],
  ["955-958", SWEETS, "Chocolate bar, milk chocolate", ["candy"]],
  ["959-961", SWEETS, "Chocolate chips", ["baking chips"]],
  ["962", SWEETS, "Chocolate coated peanuts", ["candy"], null],
  ["963", SWEETS, "Chocolate coated raisins", ["candy"], null],
  ["964", SWEETS, "Fruit leather, pieces", ["fruit snacks"], null],
  ["965-966", SWEETS, "Fruit leather, rolls", ["fruit roll ups"], null],
  ["967-968", SWEETS, "Fudge, chocolate, from recipe", ["candy"]],
  ["969-970", SWEETS, "Fudge, vanilla, from recipe", ["candy"]],
  ["971-972", SWEETS, "Gumdrops", ["candy"], null],
  ["973", SWEETS, "Gummy bears", ["candy"], null],
  ["974", SWEETS, "Gummy worms", ["candy"], null],
  ["975-976", SWEETS, "Hard candy", [], null],
  ["977-978", SWEETS, "Jelly beans", ["candy"], null],
  ["979", SWEETS, "KIT KAT bar", ["candy"], null],
  ["980-981", SWEETS, "Marshmallows", []],
  ["982-983", SWEETS, "M&M'S peanut chocolate candies", ["candy"], null],
  ["984-985", SWEETS, "M&M'S plain chocolate candies", ["candy"], null],
  ["986-987", SWEETS, "MILKY WAY bar", ["candy"], null],
  ["988", SWEETS, "REESE'S peanut butter cup", ["candy"], null],
  ["990", SWEETS, "SNICKERS bar", ["candy"], null],
  ["992", SWEETS, "SNICKERS bar", ["candy"], null],
  ["993", SWEETS, "SPECIAL DARK sweet chocolate", ["candy"], null],
  ["994", SWEETS, "STARBURST fruit chews", ["candy"], null],
  ["996-997", SWEETS, "Frosting, ready to eat", ["icing"]],
  ["998", SWEETS, "Fruit and juice bar, frozen", ["popsicle"], null],
  ["999", SWEETS, "Ice pop", ["popsicle"], null],
  ["1000", SWEETS, "Italian ices", ["sorbet"], null],
  ["1001", SWEETS, "Fruit butter, apple", ["apple butter"], null],
  ["1002-1003", SWEETS, "Gelatin dessert", ["jello"]],
  ["1004-1005", SWEETS, "Honey", [], null],
  ["1006", SWEETS, "Jams and preserves", ["jam", "jelly"], null],
  ["1008", SWEETS, "Jellies", ["jelly", "jam"], null],
  ["1010-1011", SWEETS, "Pudding, chocolate, from dry mix", []],
  ["1012-1013", SWEETS, "Pudding, vanilla, from dry mix", []],
  ["1014-1017", SWEETS, "Pudding, ready to eat", []],
  ["1018-1020", SWEETS, "Pudding, ready to eat, fat free", []],
  ["1021-1023", SWEETS, "Sugar, brown", []],
  ["1024-1026", SWEETS, "Sugar, white, granulated", []],
  ["1027-1028", SWEETS, "Sugar, powdered", ["confectioners sugar"], null],
  ["1029-1030", SWEETS, "Chocolate syrup", []],
  ["1031", SWEETS, "Corn syrup, light", [], null],
  ["1032", SWEETS, "Maple syrup", [], null],
  ["1033-1034", SWEETS, "Molasses, blackstrap", [], null],
  ["1035-1036", SWEETS, "Table syrup, pancake", ["pancake syrup"]],

  // --------------------------------------------------------------- Vegetables
  ["1037", VEG, "Alfalfa sprouts, raw", ["sprouts"], null],
  [
    "1038-1039",
    VEG,
    "Artichokes, globe or french, cooked",
    ["artichoke"],
    null,
  ],
  ["1040-1045", VEG, "Asparagus, cooked", []],
  ["1046", VEG, "Bamboo shoots, canned", [], null],
  ["1047-1048", VEG, "Lima beans, immature, frozen, cooked", ["butter beans"]],
  [
    "1049-1050",
    VEG,
    "Snap beans, cooked from raw",
    ["green beans", "string beans", "wax beans"],
  ],
  [
    "1051-1052",
    VEG,
    "Snap beans, cooked from frozen",
    ["green beans", "string beans", "wax beans"],
  ],
  [
    "1053-1054",
    VEG,
    "Snap beans, canned",
    ["green beans", "string beans", "wax beans"],
  ],
  ["1055-1056", VEG, "Bean sprouts, mung", ["sprouts"]],
  ["1057-1058", VEG, "Beets, cooked", ["beet", "beetroot"]],
  ["1059-1060", VEG, "Beets, canned", ["beet", "beetroot"]],
  ["1061", VEG, "Beet greens, cooked", ["greens"], null],
  ["1062-1063", VEG, "Black-eyed peas, immature, cooked", ["cowpeas"]],
  ["1064-1066", VEG, "Broccoli, raw", []],
  ["1067-1069", VEG, "Broccoli, cooked", []],
  ["1070-1071", VEG, "Brussels sprouts, cooked", []],
  ["1072-1073", VEG, "Cabbage, common varieties", []],
  ["1074-1075", VEG, "Cabbage, chinese, shredded", ["bok choy", "napa"]],
  ["1076", VEG, "Cabbage, red, raw, shredded", [], null],
  ["1077", VEG, "Cabbage, savoy, raw, shredded", [], null],
  ["1078", VEG, "Carrot juice, canned", ["juice"], null],
  ["1079-1081", VEG, "Carrots, raw", ["carrot"]],
  ["1082-1084", VEG, "Carrots, cooked", ["carrot"]],
  ["1085-1086", VEG, "Cauliflower, raw", [], "Raw"],
  ["1087-1089", VEG, "Cauliflower, cooked", []],
  ["1090-1091", VEG, "Celery, raw", []],
  ["1092-1093", VEG, "Celery, cooked", []],
  ["1094", VEG, "Chives, raw, chopped", ["herbs"], null],
  ["1095", VEG, "Cilantro, raw", ["coriander", "herbs"], null],
  ["1096", VEG, "Coleslaw, home prepared", ["cole slaw"], null],
  ["1097-1098", VEG, "Collards, cooked", ["collard greens", "greens"]],
  [
    "1099-1101",
    VEG,
    "Corn, sweet, yellow, cooked",
    ["sweetcorn", "corn on the cob"],
  ],
  ["1102-1103", VEG, "Corn, sweet, yellow, canned", ["sweetcorn"]],
  ["1104", VEG, "Corn, sweet, white, cooked", ["sweetcorn"], null],
  ["1105-1106", VEG, "Cucumber, peeled", ["cucumbers"]],
  ["1107-1108", VEG, "Cucumber, unpeeled", ["cucumbers"]],
  ["1109", VEG, "Dandelion greens, cooked", ["greens"], null],
  ["1110", VEG, "Dill weed, raw", ["herbs"], null],
  ["1111", VEG, "Eggplant, cooked", ["aubergine"], null],
  ["1112", VEG, "Endive, curly (escarole), raw", [], null],
  ["1113", VEG, "Garlic, raw", [], null],
  ["1114", VEG, "Hearts of palm, canned", [], null],
  ["1115", VEG, "Jerusalem artichoke, raw, sliced", ["sunchoke"], null],
  ["1116-1117", VEG, "Kale, cooked, chopped", ["greens"]],
  ["1118", VEG, "Kohlrabi, cooked, sliced", [], null],
  ["1119", VEG, "Leeks, cooked, diced", [], null],
  ["1120-1121", VEG, "Lettuce, butterhead (boston or bibb)", ["salad greens"]],
  ["1122-1124", VEG, "Lettuce, iceberg (crisphead)", ["salad greens"]],
  ["1125-1126", VEG, "Lettuce, looseleaf", ["salad greens"]],
  ["1127-1128", VEG, "Lettuce, romaine (cos)", ["salad greens"]],
  ["1129-1131", VEG, "Mushrooms", ["mushroom"]],
  ["1132-1133", VEG, "Mushrooms, shiitake", ["mushroom"]],
  ["1134", VEG, "Mustard greens, cooked", ["greens"], null],
  ["1135-1136", VEG, "Okra, sliced, cooked", []],
  ["1137-1139", VEG, "Onions, raw", ["onion"]],
  ["1140-1141", VEG, "Onions, cooked", ["onion"], "Cooked, drained"],
  ["1142", VEG, "Onions, dehydrated flakes", ["onion"], null],
  ["1143-1144", VEG, "Onions, spring, raw", ["green onions", "scallions"]],
  ["1145", VEG, "Onion rings, breaded, frozen, oven heated", [], null],
  ["1146", VEG, "Parsley, raw", ["herbs"], null],
  ["1147", VEG, "Parsnips, sliced, cooked", [], null],
  [
    "1148-1149",
    VEG,
    "Peas, edible pod, cooked",
    ["snow peas", "sugar snap peas"],
  ],
  ["1150", VEG, "Peas, green, canned", [], null],
  ["1151", VEG, "Peas, green, frozen, boiled", [], null],
  ["1152-1153", VEG, "Peppers, hot chili, raw", ["chili", "chile"]],
  ["1154", VEG, "Jalapeno peppers, canned, sliced", ["chili", "chile"], null],
  ["1155-1157", VEG, "Peppers, sweet, green, raw", ["bell pepper", "capsicum"]],
  ["1158-1159", VEG, "Peppers, sweet, red, raw", ["bell pepper", "capsicum"]],
  [
    "1160-1161",
    VEG,
    "Peppers, sweet, cooked, chopped",
    ["bell pepper", "capsicum"],
  ],
  ["1162", VEG, "Pimento, canned", [], null],
  ["1163-1165", VEG, "Potatoes, baked", ["potato"]],
  ["1166-1168", VEG, "Potatoes, boiled", ["potato"]],
  ["1169-1170", VEG, "Potatoes au gratin", ["potato"]],
  [
    "1171",
    VEG,
    "French fried potatoes, frozen, oven heated",
    ["fries", "potato"],
    null,
  ],
  ["1172-1173", VEG, "Hashed brown potatoes", ["hash browns", "potato"]],
  ["1174", VEG, "Mashed potatoes, from dehydrated flakes", ["potato"], null],
  ["1175-1176", VEG, "Mashed potatoes, home recipe", ["potato"]],
  ["1177", VEG, "Potato pancakes, home prepared", ["latkes"], null],
  ["1178", VEG, "Potato puffs, from frozen", ["tater tots"], null],
  ["1179", VEG, "Potato salad, home prepared", [], null],
  ["1180-1181", VEG, "Scalloped potatoes", ["potato"]],
  ["1182", VEG, "Pumpkin, cooked, mashed", [], null],
  ["1183", VEG, "Pumpkin, canned", [], null],
  ["1184", VEG, "Radishes, raw", ["radish"], null],
  ["1185", VEG, "Rutabagas, cooked, cubed", [], null],
  ["1186", VEG, "Sauerkraut, canned", [], null],
  ["1187", VEG, "Seaweed, kelp, raw", [], null],
  ["1188", VEG, "Seaweed, spirulina, dried", [], null],
  ["1189", VEG, "Shallots, raw, chopped", [], null],
  ["1190", VEG, "Soybeans, green, cooked", ["edamame"], null],
  ["1191-1192", VEG, "Spinach, raw", []],
  ["1193-1195", VEG, "Spinach, cooked", []],
  ["1196-1197", VEG, "Squash, summer", ["zucchini", "yellow squash"]],
  ["1198", VEG, "Squash, winter, baked, cubed", ["acorn squash"], null],
  ["1199", VEG, "Squash, winter, butternut, frozen, cooked", [], null],
  ["1200-1201", VEG, "Sweet potatoes", ["yam"]],
  ["1202", VEG, "Sweet potatoes, candied", ["yam"], null],
  ["1203-1204", VEG, "Sweet potatoes, canned", ["yam"]],
  ["1205", VEG, "Tomatillos, raw", [], null],
  ["1206-1207", VEG, "Tomatoes, raw, chopped or sliced", ["tomato"]],
  ["1208-1209", VEG, "Tomatoes, raw, whole", ["tomato", "cherry tomatoes"]],
  ["1210", VEG, "Tomatoes, canned", ["tomato"], null],
  ["1211-1212", VEG, "Tomatoes, sun dried", ["tomato"]],
  ["1213", VEG, "Tomato juice, canned", ["juice"], null],
  ["1214", VEG, "Tomato paste, canned", ["tomato"], null],
  ["1215", VEG, "Tomato puree, canned", ["tomato"], null],
  ["1216", VEG, "Tomato sauce, canned", ["tomato"], null],
  ["1217", VEG, "Tomatoes, stewed, canned", ["tomato"], null],
  ["1218", VEG, "Turnips, cooked, cubed", ["turnip"], null],
  ["1219-1220", VEG, "Turnip greens, cooked", ["greens"]],
  ["1221", VEG, "Vegetable juice cocktail, canned", ["juice", "v8"], null],
  ["1222-1223", VEG, "Mixed vegetables", []],

  // ------------------------------------------------------------ Miscellaneous
  ["1225", MISC, "Bacon bits, meatless", [], null],
  ["1226-1228", MISC, "Baking powder", []],
  ["1229", MISC, "Baking soda", [], null],
  ["1230", MISC, "Beef jerky", ["snack"], null],
  ["1231-1233", MISC, "Catsup", ["ketchup", "tomato sauce"], null],
  ["1234", MISC, "Celery seed", ["spice"], null],
  ["1235", MISC, "Chili powder", ["spice"], null],
  ["1236-1237", MISC, "Chocolate, unsweetened, baking", ["cocoa"]],
  ["1238", MISC, "Cinnamon, ground", ["spice"], null],
  ["1239-1240", MISC, "Cocoa powder, unsweetened", ["cacao"], null],
  ["1241", MISC, "Cream of tartar", [], null],
  ["1242", MISC, "Curry powder", ["spice"], null],
  ["1243", MISC, "Garlic powder", ["spice"], null],
  ["1244", MISC, "Horseradish, prepared", [], null],
  ["1245", MISC, "Mustard, prepared, yellow", [], null],
  ["1246", MISC, "Olives, pickled, green", ["olive"], null],
  ["1247", MISC, "Olives, ripe, black", ["olive"], null],
  ["1248", MISC, "Onion powder", ["spice"], null],
  ["1249", MISC, "Oregano, ground", ["spice", "herbs"], null],
  ["1250", MISC, "Paprika", ["spice"], null],
  ["1251", MISC, "Parsley, dried", ["herbs"], null],
  ["1252", MISC, "Pepper, black", ["spice"], null],
  ["1253", MISC, "Pickles, dill", ["pickle"], null],
  ["1254", MISC, "Pickles, bread and butter", ["pickle"], null],
  ["1255", MISC, "Pickle relish, sweet", [], null],
  ["1256", MISC, "Pork skins (rinds), plain", ["snack", "chicharrones"], null],
  ["1257-1262", MISC, "Potato chips", ["crisps", "snack"]],
  [
    "1263-1265",
    MISC,
    "Potato chips, made from dried potatoes",
    ["pringles", "snack"],
  ],
  ["1266", MISC, "Salt", [], null],
  ["1267", MISC, "Trail mix, regular", ["gorp", "snack"], null],
  ["1268", MISC, "Trail mix, tropical", ["snack"], null],
  ["1269", MISC, "Vanilla extract", [], null],
  ["1270", MISC, "Vinegar, cider", [], null],
  ["1271", MISC, "Vinegar, distilled", [], null],
  ["1272-1273", MISC, "Yeast, baker's, dry active", []],
  ["1274", MISC, "Yeast, baker's, compressed", [], null],
];

// Per-row repairs for measure/variant text the PDF extraction mangled.
//   variant: replacement variant text ("" removes it)
//   measure: replacement measure text (null means "show the gram weight")
//
// The printed table uses vulgar fractions (1/2 cup, 1/4 block) that the
// extraction dropped entirely, leaving a bare unit such as "cup". Those rows
// are shown by gram weight instead, which the CSV does record correctly - see
// the bare-unit handling in build-foods.mjs.
export const rowFixes = {
  40: { variant: "Powder", measure: "3 heaping tsp" },
  42: { variant: "Powder", measure: "4-5 heaping tsp" },
  55: { variant: "", measure: "1 cubic inch" },
  117: { measure: null },
  134: { variant: "Fruit flavored", measure: "8 oz container" },
  135: { variant: "Plain", measure: "8 oz container" },
  136: { variant: "Fruit flavored", measure: "8 oz container" },
  137: { variant: "Plain", measure: "8 oz container" },
  138: { variant: "Plain", measure: "8 oz container" },
  139: { variant: "Vanilla or lemon", measure: "8 oz container" },
  142: { variant: "Extra large", measure: "1 egg" },
  150: { measure: null },
  157: { variant: "Hard", measure: "1 stick" },
  162: { variant: "Hard", measure: "1 stick" },
  212: { measure: null },
  268: { measure: "portion of 21-oz can" },
  285: { variant: 'Whole (3" long)', measure: "1 fruit" },
  289: { measure: "portion of 21-oz can" },
  297: { measure: "1/2 grapefruit" },
  298: { measure: "1/2 grapefruit" },
  304: { measure: "6 fl oz can" },
  309: { measure: "6 fl oz can" },
  313: { variant: 'Raw, from 2"-dia lemon' },
  316: { variant: 'Raw, from 2"-dia lime' },
  321: { variant: "Wedge", measure: "1 wedge" },
  323: { variant: "Wedge", measure: "1 wedge" },
  330: { variant: "Raw", measure: "juice from 1 orange" },
  333: { measure: "6 fl oz can" },
  340: { variant: "Heavy syrup pack", measure: "1 half" },
  342: { variant: "Juice pack", measure: "1 half" },
  347: { variant: "Heavy syrup pack", measure: "1 half" },
  349: { variant: "Juice pack", measure: "1 half" },
  367: { variant: "Packet", measure: "1 packet (1 tbsp)" },
  371: { variant: "Large", measure: "1 strawberry" },
  372: { variant: "Medium", measure: "1 strawberry" },
  380: { variant: "", measure: '1 bagel (3" dia)' },
  381: { variant: "", measure: '1 bagel (4" dia)' },
  382: { variant: "", measure: '1 bagel (3" dia)' },
  383: { variant: "", measure: '1 bagel (4" dia)' },
  384: { variant: "", measure: '1 bagel (3" dia)' },
  385: { variant: "", measure: '1 bagel (4" dia)' },
  389: { variant: "With 2% milk", measure: '1 biscuit (2" dia)' },
  390: { variant: "With 2% milk", measure: '1 biscuit (4" dia)' },
  391: { variant: "Regular", measure: '1 biscuit (2" dia)' },
  392: { variant: "Lower fat", measure: '1 biscuit (2" dia)' },
  394: { variant: "", measure: "1 slice" },
  395: { variant: "", measure: "1 slice" },
  396: { variant: "", measure: '1 bread (5" dia)' },
  397: { variant: "", measure: '1 bread (10" dia)' },
  403: { variant: "", measure: '1 pita (4" dia)' },
  404: { variant: "", measure: '1 pita (6" dia)' },
  522: { measure: "1 oz" },
  571: { measure: "1 croissant" },
  575: { variant: "", measure: "1 hole" },
  577: { variant: "", measure: "1 hole" },
  579: { measure: "1 eclair" },
  589: { measure: "1 matzo" },
  603: { measure: "1 oz" },
  722: { measure: "1 oz (142 seeds)" },
  728: { variant: "Firm", measure: "1/4 block" },
  807: { variant: "Frozen", measure: null },
  809: { measure: "1 croissant" },
  834: { measure: "1 enchilada" },
  868: { variant: "Breast (5.6 oz with bones)", measure: "1/2 breast" },
  872: { variant: "Breast (4.2 oz with bones)", measure: "1/2 breast" },
  876: { variant: "Breast (4.2 oz with bone and skin)", measure: "1/2 breast" },
  883: { measure: "1/2 duck" },
  887: { variant: "Patty", measure: "1 patty (from 4 oz raw)" },
  894: { measure: "5 oz package" },
  895: { variant: "", measure: "1 patty (2.25 oz)" },
  944: { variant: "Tomato chili", measure: null },
  947: { variant: "Chicken", measure: null },
  948: { variant: "Country sausage", measure: null },
  951: { measure: "1 fun size bar" },
  973: { measure: "10 bears" },
  974: { measure: "10 worms" },
  981: { variant: "Regular", measure: "1 marshmallow" },
  986: { measure: "1 fun size bar" },
  988: { measure: "1 miniature cup" },

  993: { measure: "1 miniature bar" },
  996: { variant: "Chocolate", measure: "1/12 package" },
  997: { variant: "Vanilla", measure: "1/12 package" },
  1079: { variant: 'Whole, 7" long', measure: "1 carrot" },
  1133: { variant: "Dried", measure: "1 mushroom" },
  1138: { variant: "Whole", measure: '1 onion (2" dia)' },
  1144: { variant: "Whole", measure: '1 onion (4" long)' },
  1154: { measure: null },
  1165: { variant: "Skin only", measure: "1 skin" },
  1171: { measure: "10 strips" },
  1178: { measure: "10 puffs" },
};

// Bare countable nouns left without their leading "1" by the extraction.
export const countableUnits = new Set([
  "bagel",
  "bar",
  "biscuit",
  "block",
  "fillet",
  "package",
  "slice",
]);
